//! IEEE-754 encode/decode round-trip, ported from `test_float`
//! (libqalculate `src/test.cc:2257-2273`).
//!
//! The reference's `main()` drives it like this (`test.cc:2615-2630`):
//!
//! ```text
//! for(long int i = 0; i < 1000000L; i++) {
//!     nr.set(rnd_number(false, false, false, false, false));
//!     if(i % 2 == 1) nr.exp2(rand() % 2200 - 1100);
//!     if(!test_float(nr)) return 0;
//! }
//! ```
//!
//! — two million random values, half of them scaled by a random power of two
//! in `[-1100, 1100]`, each pushed through `to_float`/`from_float` at
//! `BASE_FP64`. A failure it finds cannot be reproduced: the seed is the wall
//! clock. **This port uses a fixed corpus instead**, generated by a SplitMix64
//! seeded with a constant ([`fp_roundtrip::SEED`]), so the same values are
//! tested on every run on every machine — and it runs all five widths
//! `qalc-num` implements (FP16, FP32, FP64, FP80, FP128) rather than only the
//! one `test_float` hard-codes.
//!
//! # The property
//!
//! `test_float` checks two things, and the second is not the one the width of
//! the value would suggest:
//!
//! 1. `nr.print(BASE_FPn)` is `to_float(nr, n)` — the printer and the encoder
//!    agree. In this port `Number::print` delegates to
//!    [`qalc_num::ieee::to_float`] and then groups the bits in fours, so this
//!    is a check on the *grouping*, and it is kept because the grouping is
//!    what the `numberbase.batch` transcript pins.
//! 2. `from_float(to_float(nr)) ` re-encodes to the *same bit string*. Note
//!    that this is not `from_float(to_float(nr)) == nr`: encoding is lossy for
//!    all but the dyadic rationals, so equality with `nr` would fail for `1/3`
//!    at every width. What must hold is that decoding lands on a value the
//!    encoder maps back to where it came from — i.e. that `from_float` is a
//!    section of `to_float`. That is the strongest statement that is true of
//!    every input, and it is exactly what catches an off-by-one in the
//!    exponent bias, a mis-placed implicit leading bit, or a subnormal decoded
//!    at the wrong scale.
//!
//! The C++ carries one documented exception, ported verbatim in
//! [`fp_roundtrip::NEGATIVE_ZERO_EXCEPTION`]: a value that underflows to
//! *negative* zero encodes as `1000…0`, decodes to `0`, and re-encodes as
//! `0000…0`. `Number` has no signed zero, so the sign is genuinely
//! unrecoverable and the reference accepts it.
//!
//! # What it found
//!
//! 55 955 `(value, width)` pairs — 186 values across five widths, plus five of
//! them scaled by every power of two in `[-1100, 1100]`:
//!
//! | | first run | now |
//! |---|---|---|
//! | held | 42 686 | 53 865 |
//! | failed | 11 180 — every one of them FP80 | 0 |
//! | out of scope (negative zero, the C++'s own exception) | 2 089 | 2 090 |
//!
//! **`to_float` was wrong for the whole 80-bit x87 format**: it dropped the
//! explicit integer bit the format exists to store, so every finite non-zero
//! value encoded one bit to the left of where it belonged. The reference says
//! `1 to fp80` is `0011 1111 1111 1111 1000 …`; this port said `0011 1111 1111
//! 1111 0000 …`. `from_float`'s 80-bit branch was the correct half, which is
//! why the round trip caught it: decoding the port's own FP80 output for `1`,
//! `2`, `1024` — any value whose leading significand bit was the only one set
//! — gave `0`. The other four widths were clean across the whole corpus.
//!
//! The cause was in the encoder's *fractional* bit count. `to_float` rounded
//! the significand to `mbits + 1 = 64` fractional bits at 80 bits wide and
//! then masked the result back to the 64-bit field, which shifted the value
//! one place left and threw the integer bit away. The C++ rounds to
//! `bits - expbits - (bits == 80 ? 2 : 1)` fractional bits at *every* width —
//! 63 for FP80 (`Number.cc:10551-10552`) — and, for 80 bits only, prepends the
//! integer digit it printed (`Number.cc:10597`), giving a field of 1 integer
//! bit + 63 fraction bits. The fix rounds to `mbits` fractional bits
//! unconditionally and lets the 80-bit mask keep the whole result;
//! 11 179 pairs moved to `held` and one to the negative-zero exception.
//!
//! Nothing in `libqalculate/tests` mentions `fp16`, `fp80` or `fp128`; the
//! only float the 656 transcript assertions exercise is FP32. That is why a
//! defect this total survived to be found here.
//!
//! # KNOWN_FAILURES
//!
//! Same contract as `crates/qalc-num/tests/interval_closure.rs` and
//! `crates/qalc-core/tests/evaluation_invariants.rs`: every failure is listed
//! with a diagnosis, a new one fails the test, and a listed one that has
//! started passing *also* fails the test. The list can only shrink. Nothing
//! here is fixed by this file.
//!
//! # Proving the check can fail
//!
//! [`the_check_catches_a_biased_exponent`] and
//! [`the_check_catches_a_dropped_implicit_bit`] re-implement `to_float`'s
//! decode side with one defect each and assert the comparison rejects it. A
//! round-trip property is the easiest kind of test to write so that it cannot
//! fail — compose two functions that are inverse *by construction* and it is
//! green forever.

use std::collections::BTreeSet;

mod fp_roundtrip {
    use qalc_num::options::base;
    use qalc_num::{ieee, Number, PrintOptions};
    use num_bigint::BigInt;
    use num_rational::BigRational;

    /// The five widths `qalc-num/src/number/ieee.rs` implements, with the
    /// `BASE_FP*` constant the printer selects them by.
    pub const WIDTHS: &[(&str, u32, i32)] = &[
        ("fp16", 16, base::FP16),
        ("fp32", 32, base::FP32),
        ("fp64", 64, base::FP64),
        ("fp80", 80, base::FP80),
        ("fp128", 128, base::FP128),
    ];

    /// Fixed, so the corpus is the same on every run. Changing it changes
    /// which values are tested and invalidates every `rnd:*` ledger entry.
    pub const SEED: u64 = 0x5150_1CA1_C0FF_EE01;

    /// SplitMix64 — three lines, no dependency, and reproducible across
    /// platforms because every operation is on a `u64` with defined wrapping.
    pub struct SplitMix64(u64);

    impl SplitMix64 {
        pub fn new(seed: u64) -> SplitMix64 {
            SplitMix64(seed)
        }
        pub fn next(&mut self) -> u64 {
            self.0 = self.0.wrapping_add(0x9E37_79B9_7F4A_7C15);
            let mut z = self.0;
            z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
            z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
            z ^ (z >> 31)
        }
        /// A non-zero value with at most `bits` significant bits.
        pub fn bounded(&mut self, bits: u32) -> u64 {
            let mask = if bits >= 64 { u64::MAX } else { (1u64 << bits) - 1 };
            (self.next() & mask).max(1)
        }
    }

    fn rational(num: i64, den: i64) -> Number {
        Number::from_ints(num, den, 0)
    }

    fn big_rational(num: BigInt, den: BigInt) -> Number {
        Number::from_rational(BigRational::new(num, den))
    }

    /// Named values chosen to sit on the encoder's decision points, rather
    /// than drawn at random: exact halves and quarters (encode exactly),
    /// non-dyadic rationals (must round), values whose significand is a run of
    /// ones (rounding carries into the next binade), and the two transcript
    /// values `numberbase.batch` pins.
    pub fn fixed_corpus() -> Vec<(String, Number)> {
        let mut out: Vec<(String, Number)> = Vec::new();
        let mut push = |label: &str, n: Number| out.push((label.to_string(), n));

        push("zero", Number::new());
        push("one", Number::from_i64(1));
        push("minus-one", Number::from_i64(-1));
        push("two", Number::from_i64(2));
        push("half", rational(1, 2));
        push("minus-half", rational(-1, 2));
        push("quarter", rational(1, 4));
        push("three", Number::from_i64(3));
        push("minus-three", Number::from_i64(-3));
        push("ten", Number::from_i64(10));
        push("1024", Number::from_i64(1024));
        push("third", rational(1, 3));
        push("minus-third", rational(-1, 3));
        push("two-sevenths", rational(2, 7));
        push("22/7", rational(22, 7));
        push("355/113", rational(355, 113));
        // `52.345 to float` and `floatError(52.345)`, numberbase.batch.
        push("52.345", rational(52345, 1000));
        push("0.1", rational(1, 10));
        push("-0.1", rational(-1, 10));
        push("1e10", Number::from_i64(10_000_000_000));
        push("1e-10", rational(1, 10_000_000_000));
        push("123456789", Number::from_i64(123_456_789));
        push("i64-max", Number::from_i64(i64::MAX));

        // Significands that are a solid run of ones: the encoder must carry
        // the rounding into the exponent rather than wrapping the mantissa.
        for k in [11u32, 24, 53, 64, 113] {
            let ones = (BigInt::from(1) << k as usize) - BigInt::from(1);
            push(
                &format!("ones-{k}"),
                big_rational(ones.clone(), BigInt::from(1)),
            );
            // 1 + (2^k - 1)/2^k: just under 2, at every width's precision.
            push(
                &format!("just-under-two-{k}"),
                big_rational(
                    (BigInt::from(1) << (k + 1) as usize) - BigInt::from(1),
                    BigInt::from(1) << k as usize,
                ),
            );
            // Exactly a tie: …1000…0 with one bit past the last kept bit, so
            // round-half-to-even has to choose.
            push(
                &format!("exact-tie-{k}"),
                big_rational(
                    (BigInt::from(1) << (k + 1) as usize) + BigInt::from(1),
                    BigInt::from(1) << k as usize,
                ),
            );
        }

        // The overflow and underflow edges of each width, from the outside in:
        // 2^(expbias+1) is the first value that cannot be represented, and
        // 2^(1-expbias-mantissabits) the last subnormal.
        for (name, bits, _) in WIDTHS {
            let expbits = ieee::standard_expbits(*bits);
            let expbias = (1i64 << (expbits - 1)) - 1;
            let mbits = bits - expbits - if *bits == 80 { 2 } else { 1 };
            for (tag, e) in [
                ("max-exp", expbias),
                ("over-max", expbias + 1),
                ("min-normal", 1 - expbias),
                ("min-subnormal", 1 - expbias - mbits as i64),
                ("under-min", -expbias - mbits as i64),
            ] {
                let mut n = Number::from_i64(1);
                assert!(n.exp2_mul(&Number::from_i64(e)), "2^{e} is representable");
                push(&format!("{name}-{tag}"), n.clone());
                assert!(n.negate());
                push(&format!("{name}-{tag}-neg"), n);
            }
        }

        let mut inf = Number::new();
        inf.set_plus_infinity(false, false);
        push("plus-infinity", inf);
        let mut ninf = Number::new();
        ninf.set_minus_infinity(false, false);
        push("minus-infinity", ninf);

        out
    }

    /// `rnd_number`'s stand-in: 96 quotients of pseudo-random integers, at
    /// three magnitudes, from [`SEED`]. The C++ draws a fresh one two million
    /// times; a fixed 96 that are the *same* 96 on every run is worth more,
    /// and the fixed corpus above is what covers the edges a random draw would
    /// almost never hit.
    pub fn random_corpus() -> Vec<(String, Number)> {
        let mut rng = SplitMix64::new(SEED);
        let mut out = Vec::new();
        for round in 0..32 {
            for bits in [16u32, 32, 63] {
                let num = rng.bounded(bits) as i64;
                let den = rng.bounded(bits) as i64;
                let sign = if rng.next() & 1 == 0 { 1 } else { -1 };
                out.push((
                    format!("rnd-{bits}-{round}"),
                    rational(sign * num, den),
                ));
            }
        }
        out
    }

    /// The `nr.exp2(rand() % 2200 - 1100)` half of the C++ driver, made
    /// deterministic: every integer in `[-1100, 1100]`, applied to the
    /// [`SCALED_BASE`] values.
    pub fn k_values() -> Vec<i64> {
        (-1100..=1100).collect()
    }

    /// The values that get scaled. Deliberately short — the scaling loop is
    /// `SCALED_BASE.len() * 2201 * 5` round trips, so each entry costs about
    /// eleven thousand of them. One exact power of two, one dyadic that is not
    /// a power of two, one non-dyadic, one negative, and one whose significand
    /// forces a rounding carry.
    pub const SCALED_BASE: &[&str] = &["one", "52.345", "third", "minus-third", "just-under-two-53"];

    /// What one `(value, width)` pair did.
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub enum Outcome {
        Held,
        /// Out of scope, with the reason.
        Skipped(String),
        Failed(String),
    }

    /// `test_float`'s documented escape hatch (`test.cc:2268`): a value that
    /// underflows to negative zero encodes as `1` followed by zeros, decodes
    /// to plain zero — `Number` has no signed zero — and re-encodes with the
    /// sign bit clear. The information is not recoverable, so the reference
    /// accepts it and so does this.
    pub const NEGATIVE_ZERO_EXCEPTION: &str =
        "underflowed to negative zero; Number has no signed zero (test.cc:2268)";

    fn strip(bits: &str) -> String {
        bits.chars().filter(|c| *c == '0' || *c == '1').collect()
    }

    /// The whole of `test_float`, for one value at one width.
    pub fn check(n: &Number, bits: u32, fp_base: i32) -> Outcome {
        let Some(encoded) = ieee::to_float(n, bits, 0) else {
            return Outcome::Skipped("to_float declined the value".into());
        };
        if encoded.len() != bits as usize {
            return Outcome::Failed(format!(
                "to_float returned {} bits, not {bits}: {encoded}",
                encoded.len()
            ));
        }

        // (1) The printer agrees with the encoder, modulo the grouping in
        // fours that `Number::print` adds and `test.cc`'s
        // BASE_DISPLAY_NONE suppresses.
        let po = PrintOptions {
            base: fp_base,
            ..PrintOptions::default()
        };
        let printed = n.print(&po);
        if strip(&printed) != encoded {
            return Outcome::Failed(format!(
                "print(BASE_FP{bits}) = {printed}   but to_float = {encoded}"
            ));
        }

        // (2) Decoding and re-encoding returns to the same bit string.
        let Some(decoded) = ieee::from_float(&encoded, bits, 0) else {
            return Outcome::Failed(format!("from_float refused its own output: {encoded}"));
        };
        let Some(again) = ieee::to_float(&decoded, bits, 0) else {
            return Outcome::Failed(format!(
                "to_float declined from_float's output for {encoded}"
            ));
        };
        if again == encoded {
            return Outcome::Held;
        }
        if decoded.is_zero() && encoded.starts_with('1') && !encoded[1..].contains('1') {
            return Outcome::Skipped(NEGATIVE_ZERO_EXCEPTION.into());
        }
        Outcome::Failed(format!(
            "round trip moved: to_float = {encoded}, from_float -> to_float = {again}"
        ))
    }

    /// `(label, value, width)` for every pair the suite checks, in a stable
    /// order.
    pub fn plan() -> Vec<(String, Number, u32, i32)> {
        let fixed = fixed_corpus();
        let mut out = Vec::new();
        for (label, n) in fixed.iter().chain(random_corpus().iter()) {
            for (wname, bits, fp_base) in WIDTHS {
                out.push((format!("{label} @ {wname}"), n.clone(), *bits, *fp_base));
            }
        }
        let ks = k_values();
        for base_label in SCALED_BASE {
            let (_, base_value) = fixed
                .iter()
                .find(|(l, _)| l == base_label)
                .unwrap_or_else(|| panic!("SCALED_BASE names `{base_label}`, not in the corpus"));
            for k in &ks {
                let mut n = base_value.clone();
                assert!(
                    n.exp2_mul(&Number::from_i64(*k)),
                    "scaling {base_label} by 2^{k} failed"
                );
                for (wname, bits, fp_base) in WIDTHS {
                    out.push((
                        format!("{base_label}*2^{k} @ {wname}"),
                        n.clone(),
                        *bits,
                        *fp_base,
                    ));
                }
            }
        }
        out
    }
}

/// Pairs that do not round-trip, and why: `(label glob, exact count,
/// diagnosis)`.
///
/// The glob is either a literal `"<value> @ <width>"` label, as
/// [`fp_roundtrip::plan`] generates, or a `*`-prefixed suffix match. A
/// wildcard is allowed because a defect can be a whole format rather than a
/// scattering of awkward values, and writing out eleven thousand
/// identically-diagnosed labels would bury the diagnosis rather than record
/// it. The `count` is what keeps that from being a blanket exemption: it is
/// checked for **exact** equality, so one more pair breaking under a wildcard
/// fails the test just as loudly as an unglobbed one would, and a repair that
/// fixes half the class fails it too until the number comes down. Same
/// contract as `interval_closure.rs`, expressed per class instead of per row.
///
/// Empty: the one class this suite ever recorded — the entire FP80 format,
/// 11 180 pairs — was the encoder rounding the significand to `mbits + 1`
/// fractional bits instead of `mbits` and then masking the x87 explicit
/// integer bit off the front of the result. Fixed in
/// `qalc-num/src/number/ieee.rs`; see the module header above for the
/// before/after counts. The list can only shrink, so it stays empty unless a
/// genuinely new failure is diagnosed into it.
const KNOWN_FAILURES: &[(&str, usize, &str)] = &[];

/// True when `label` is covered by a [`KNOWN_FAILURES`] glob. `*` is only
/// meaningful as the first character, and means "any prefix".
fn glob_matches(glob: &str, label: &str) -> bool {
    match glob.strip_prefix('*') {
        Some(suffix) => label.ends_with(suffix),
        None => glob == label,
    }
}

/// The whole plan, evaluated once and shared.
fn results() -> &'static [(String, fp_roundtrip::Outcome)] {
    static ROWS: std::sync::OnceLock<Vec<(String, fp_roundtrip::Outcome)>> =
        std::sync::OnceLock::new();
    ROWS.get_or_init(|| {
        let plan = fp_roundtrip::plan();
        let workers = std::thread::available_parallelism()
            .map_or(4, |n| n.get())
            .clamp(1, 8);
        let chunk = plan.len().div_ceil(workers);
        let parts: Vec<Vec<(String, fp_roundtrip::Outcome)>> = std::thread::scope(|s| {
            let handles: Vec<_> = plan
                .chunks(chunk)
                .map(|c| {
                    s.spawn(move || {
                        c.iter()
                            .map(|(label, n, bits, fp_base)| {
                                (label.clone(), fp_roundtrip::check(n, *bits, *fp_base))
                            })
                            .collect::<Vec<_>>()
                    })
                })
                .collect();
            handles.into_iter().map(|h| h.join().unwrap()).collect()
        });
        parts.into_iter().flatten().collect()
    })
}

#[test]
fn decoding_and_re_encoding_returns_the_same_bits() {
    let rows = results();

    let mut held = 0usize;
    let mut skips: std::collections::BTreeMap<String, usize> = Default::default();
    let mut failures: Vec<(String, String)> = Vec::new();
    for (label, outcome) in rows {
        match outcome {
            fp_roundtrip::Outcome::Held => held += 1,
            fp_roundtrip::Outcome::Skipped(reason) => {
                *skips.entry(reason.clone()).or_default() += 1
            }
            fp_roundtrip::Outcome::Failed(why) => failures.push((label.clone(), why.clone())),
        }
    }

    println!(
        "\nP6 IEEE round trip\n  {} (value, width) pair(s): {held} held, {} failed, {} out of scope",
        rows.len(),
        failures.len(),
        skips.values().sum::<usize>()
    );
    for (reason, count) in &skips {
        println!("    out of scope ({count}): {reason}");
    }

    // Every failure has to be covered by a ledger glob, and every glob has to
    // cover exactly as many as it says. Checking the count in both directions
    // is what makes a wildcard entry safe: it cannot absorb a new failure, and
    // it cannot outlive a partial repair.
    let mut counts = vec![0usize; KNOWN_FAILURES.len()];
    let mut new: Vec<String> = Vec::new();
    for (label, why) in &failures {
        match KNOWN_FAILURES
            .iter()
            .position(|(glob, _, _)| glob_matches(glob, label))
        {
            Some(i) => counts[i] += 1,
            None => new.push(format!("  {label}\n      {why}")),
        }
    }
    assert!(held > 0, "every pair was skipped — the property tested nothing");
    assert!(
        new.is_empty(),
        "{} (value, width) pair(s) newly fail the IEEE round trip. Either the \
         change that caused it is a regression, or add them to KNOWN_FAILURES \
         with a diagnosis:\n{}",
        new.len(),
        new.join("\n")
    );
    for (i, (glob, want, _)) in KNOWN_FAILURES.iter().enumerate() {
        assert_eq!(
            counts[i], *want,
            "KNOWN_FAILURES entry `{glob}` covers {} pair(s), not the {want} \
             it records. If the count went down, lower it, so the recorded \
             total cannot creep back up; if it went up, the extra pairs are a \
             regression the wildcard is hiding.",
            counts[i]
        );
    }
}

/// The plan's shape, pinned so a corpus that quietly shrank cannot leave the
/// suite green while testing a fraction of the surface.
#[test]
fn the_corpus_is_the_size_it_should_be() {
    let plan = fp_roundtrip::plan();
    let labels: BTreeSet<&str> = plan.iter().map(|(l, _, _, _)| l.as_str()).collect();
    assert_eq!(labels.len(), plan.len(), "pair labels are not unique");

    let fixed = fp_roundtrip::fixed_corpus().len();
    let random = fp_roundtrip::random_corpus().len();
    let scaled = fp_roundtrip::SCALED_BASE.len() * fp_roundtrip::k_values().len();
    assert_eq!(
        plan.len(),
        (fixed + random + scaled) * fp_roundtrip::WIDTHS.len()
    );
    assert_eq!(fp_roundtrip::k_values().len(), 2201, "k spans [-1100, 1100]");
    println!(
        "corpus: {fixed} fixed values + {random} seeded values + {scaled} scaled, \
         across {} widths = {} pairs",
        fp_roundtrip::WIDTHS.len(),
        plan.len()
    );
}

/// Prints `label<TAB>outcome` for every pair and nothing else. Not part of the
/// suite — it exists to rebuild [`KNOWN_FAILURES`] and to see a whole failure
/// class at once:
///
/// ```text
/// cargo test -q -p qalc-num --test ieee_roundtrip -- --ignored --nocapture worker
/// ```
#[test]
#[ignore = "diagnostic tool, not an assertion"]
fn worker() {
    for (label, outcome) in results() {
        let s = match outcome {
            fp_roundtrip::Outcome::Held => "HELD".to_string(),
            fp_roundtrip::Outcome::Skipped(r) => format!("SKIP\t{r}"),
            fp_roundtrip::Outcome::Failed(w) => format!("FAIL\t{w}"),
        };
        println!("{label}\t{s}");
    }
}

/// The ledger has to stay honest on its own terms, independently of whether
/// the arithmetic agrees: every glob names pairs that exist, no glob is
/// redundant with another, and every entry carries a real diagnosis rather
/// than a placeholder.
#[test]
fn the_failure_ledger_is_well_formed() {
    let labels: Vec<String> = fp_roundtrip::plan()
        .into_iter()
        .map(|(l, _, _, _)| l)
        .collect();
    let mut seen: BTreeSet<&str> = BTreeSet::new();
    for (glob, count, why) in KNOWN_FAILURES {
        let hits = labels.iter().filter(|l| glob_matches(glob, l)).count();
        assert!(
            hits > 0,
            "ledger glob `{glob}` matches no pair in the plan"
        );
        assert!(
            *count <= hits,
            "ledger glob `{glob}` records {count} failures but only matches \
             {hits} pairs at all"
        );
        assert!(seen.insert(glob), "ledger lists `{glob}` twice");
        assert!(
            why.len() > 20 && !why.contains("TODO") && !why.contains("???"),
            "ledger entry for `{glob}` is not a diagnosis: {why:?}"
        );
    }
    // No pair may be claimed by two globs, or the counts would double-count.
    for label in &labels {
        let n = KNOWN_FAILURES
            .iter()
            .filter(|(g, _, _)| glob_matches(g, label))
            .count();
        assert!(n <= 1, "{label} is matched by {n} ledger globs");
    }
}

// =====================================================================
// Proving the check can fail
// =====================================================================
//
// A round-trip test over `f` and `f⁻¹` is the easiest property in this
// codebase to write so that it is green no matter what: if the decoder is
// derived from the encoder, the two agree on their shared mistakes. Both
// tests below inject a defect into a *re-implementation* of the decoder and
// assert the comparison rejects it, which is the only way to know the
// comparison has teeth.

/// A deliberately wrong decoder: exponent bias off by one.
///
/// This is the single most likely `from_float` bug — the bias is
/// `2^(expbits-1) - 1`, and `2^(expbits-1)` is the obvious wrong answer — and
/// it is invisible to any test that only checks `to_float`'s output against a
/// hand-computed constant.
fn decode_with_bias_error(bits_str: &str, bits: u32) -> qalc_num::Number {
    use num_bigint::BigInt;
    use num_rational::BigRational;
    use num_traits::One;

    let expbits = qalc_num::ieee::standard_expbits(bits) as usize;
    let b: Vec<u8> = bits_str.bytes().collect();
    let neg = b[0] == b'1';
    let mut exp: i64 = 0;
    for i in 1..=expbits {
        exp = exp * 2 + i64::from(b[i] == b'1');
    }
    // The defect: `1 << (expbits - 1)` where `from_float` has `- 1`.
    let expbias: i64 = 1i64 << (expbits - 1);
    let e = exp - expbias;
    let mut frac = if exp == 0 {
        BigRational::from_integer(BigInt::from(0))
    } else {
        BigRational::one()
    };
    let mut step = BigRational::new(BigInt::one(), BigInt::from(2));
    for i in (expbits + 1)..bits as usize {
        if b[i] == b'1' {
            frac += &step;
        }
        step /= BigInt::from(2);
    }
    let scale = BigRational::from_integer(BigInt::one() << e.unsigned_abs() as usize);
    let value = if e >= 0 { frac * scale } else { frac / scale };
    qalc_num::Number::from_rational(if neg { -value } else { value })
}

#[test]
fn the_check_catches_a_biased_exponent() {
    let n = qalc_num::Number::from_ints(52345, 1000, 0);
    let encoded = qalc_num::ieee::to_float(&n, 32, 0).expect("52.345 encodes at FP32");

    // The real decoder round-trips.
    let good = qalc_num::ieee::from_float(&encoded, 32, 0).expect("decodes");
    assert_eq!(
        qalc_num::ieee::to_float(&good, 32, 0).as_deref(),
        Some(encoded.as_str()),
        "the unmodified round trip must hold, or this test proves nothing"
    );

    // The off-by-one bias does not.
    let bad = decode_with_bias_error(&encoded, 32);
    let again = qalc_num::ieee::to_float(&bad, 32, 0).expect("re-encodes");
    assert_ne!(
        again, encoded,
        "an exponent bias off by one survived the round-trip check — the \
         check has no teeth"
    );
}

/// A second injected defect, on the other half of the format: dropping the
/// implicit leading `1` of a normal significand.
///
/// A decoder that forgets it produces a value in `[0, 1)` instead of `[1, 2)`,
/// which re-encodes with a different exponent *and* a different mantissa. If
/// the round-trip comparison were, say, only checking the bit *length*, this
/// would pass.
#[test]
fn the_check_catches_a_dropped_implicit_bit() {
    use num_bigint::BigInt;
    use num_rational::BigRational;

    for (bits, label) in [(16u32, "fp16"), (32, "fp32"), (64, "fp64"), (128, "fp128")] {
        let n = qalc_num::Number::from_ints(22, 7, 0);
        let encoded = qalc_num::ieee::to_float(&n, bits, 0).expect("22/7 encodes");
        let expbits = qalc_num::ieee::standard_expbits(bits) as usize;
        let b: Vec<u8> = encoded.bytes().collect();
        let mut exp: i64 = 0;
        for i in 1..=expbits {
            exp = exp * 2 + i64::from(b[i] == b'1');
        }
        let expbias: i64 = (1i64 << (expbits - 1)) - 1;
        let e = exp - expbias;
        // The defect: `frac` starts at 0 instead of 1 for a normal value.
        let mut frac = BigRational::from_integer(BigInt::from(0));
        let mut step = BigRational::new(BigInt::from(1), BigInt::from(2));
        for i in (expbits + 1)..bits as usize {
            if b[i] == b'1' {
                frac += &step;
            }
            step /= BigInt::from(2);
        }
        let scale = BigRational::from_integer(BigInt::from(1) << e.unsigned_abs() as usize);
        let value = if e >= 0 { frac * scale } else { frac / scale };
        let bad = qalc_num::Number::from_rational(value);
        let again = qalc_num::ieee::to_float(&bad, bits, 0).expect("re-encodes");
        assert_ne!(
            again, encoded,
            "at {label}, dropping the implicit leading bit survived the \
             round-trip check"
        );
    }
}
